# Generated by Django 3.0.8 on 2020-08-15 03:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_userpotrait_userverified'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.User')),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('session_id', models.CharField(max_length=256)),
                ('expiration_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
            ],
            bases=('feed.user',),
        ),
    ]
