# Generated by Django 3.0.8 on 2020-10-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_postinteractiontracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='portrait',
        ),
        migrations.AddField(
            model_name='user',
            name='portrait_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
